(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require int.Int.
Require int.Abs.
Require int.ComputerDivision.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | mk_ref : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments mk_ref {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | mk_ref x => x
  end.

(* Why3 goal *)
Theorem VC_somme :
  forall (n:Z), (0%Z <= n)%Z ->
  (0%Z = (ZArith.BinInt.Z.quot ((0%Z * 0%Z)%Z + 1%Z)%Z 2%Z)) /\
  forall (r:Z) (i:Z), (r = (ZArith.BinInt.Z.quot ((i * i)%Z + 1%Z)%Z 2%Z)) ->
  ((i < n)%Z -> forall (i1:Z), (i1 = (i + 1%Z)%Z) -> forall (r1:Z),
   (r1 = (r + i1)%Z) ->
   ((0%Z <= (n - i)%Z)%Z /\ ((n - i1)%Z < (n - i)%Z)%Z) /\
   (r1 = (ZArith.BinInt.Z.quot ((i1 * i1)%Z + 1%Z)%Z 2%Z))) /\
  (~ (i < n)%Z -> (r = (ZArith.BinInt.Z.quot ((n * n)%Z + 1%Z)%Z 2%Z))).
Proof.
intros n h1.

Qed.

